import { useState, FormEvent, useEffect } from 'react'
import './dashboard.css'

interface ClockInModalProps {
  isOpen: boolean
  onClose: () => void
  onClockIn: (employeeID: string, dailyCode: string) => void
}

const ClockInModal = ({ isOpen, onClose, onClockIn }: ClockInModalProps) => {
  const [employeeID, setEmployeeID] = useState("")
  const [dailyCode, setDailyCode] = useState("")
  const [showCode, setShowCode] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState("")
  const [showSuccess, setShowSuccess] = useState(false)
  const [showFailed, setShowFailed] = useState(false)
  const [clockInTime, setClockInTime] = useState<Date | null>(null)

  useEffect(() => {
    if (isOpen) {
      setClockInTime(new Date())
      setError("")
      setShowSuccess(false)
      setShowFailed(false)
      // Auto-generate unique employee ID (will come from auth later)
      setEmployeeID("EMP" + Math.random().toString(36).substr(2, 6).toUpperCase())
      setDailyCode("")
      setShowCode(false)
    }
  }, [isOpen])

  if (!isOpen) return null

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault()
    setError("")

    if (!employeeID.trim() || !dailyCode.trim()) {
      setError("Please enter the daily passcode")
      return
    }

    setIsLoading(true)
    
    try {
      await onClockIn(employeeID.trim(), dailyCode)
      setIsLoading(false)
      setShowSuccess(true)
      
      setTimeout(() => {
        setShowSuccess(false)
        onClose()
      }, 1500)
    } catch (error: any) {
      setIsLoading(false)
      setShowFailed(true)
      setError(error?.message || "Invalid passcode. Please try again.")
      
      setTimeout(() => {
        setShowFailed(false)
      }, 3000)
    }
  }

  return (
    <div className="modalOverlay">
      <div className="modalBackdrop" onClick={onClose} />
      
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="modalHeader">
          <div>
            <h2>Clock In</h2>
            {clockInTime && (
              <p className="modalTime">
                Time: {clockInTime.toLocaleTimeString("en-US", {
                  hour: "2-digit",
                  minute: "2-digit",
                  second: "2-digit",
                  hour12: true,
                })}
              </p>
            )}
          </div>
          <button onClick={onClose} className="modalClose">
            <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <form onSubmit={handleSubmit} className="modalBody">
          {error && !showSuccess && !showFailed && (
            <div className="modalError">{error}</div>
          )}

          {showSuccess && (
            <div className="modalSuccess">
              <div className="successIcon">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <p className="successTitle">Successfully Clocked In!</p>
              <p className="successSubtitle">You can now start tracking your time</p>
            </div>
          )}

          {showFailed && (
            <div className="modalFailed">
              <div className="failedIcon">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </div>
              <p className="failedTitle">Clock In Failed</p>
              <p className="failedSubtitle">Please check your passcode and try again</p>
            </div>
          )}

          {!showSuccess && !showFailed && (
            <div className="modalForm">
              <div className="modalInfo">
                <svg viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                </svg>
                <p>
                  <strong>Note:</strong> The daily passcode is generated by your administrator. Please contact them if you don't have today's passcode.
                </p>
              </div>

              <div className="formGroup">
                <label>Employee ID</label>
                <input
                  type="text"
                  value={employeeID}
                  className="formInput"
                  placeholder="Your employee ID"
                  readOnly
                  style={{ backgroundColor: 'var(--color-white-smoke-1)', cursor: 'not-allowed' }}
                />
                <p style={{ fontSize: '12px', color: 'var(--color-slate-gray)', margin: '4px 0 0' }}>
                  Your employee ID: <b>{employeeID}</b>
                </p>
              </div>

              <div className="formGroup">
                <label>Daily Passcode</label>
                <div className="inputWrapper">
                  <input
                    type={showCode ? "text" : "password"}
                    value={dailyCode}
                    onChange={(e) => setDailyCode(e.target.value)}
                    className="formInput"
                    placeholder="Enter today's daily passcode"
                    disabled={isLoading}
                    autoFocus
                  />
                  <button
                    type="button"
                    onClick={() => setShowCode(!showCode)}
                    className="inputIconBtn"
                  >
                    {showCode ? (
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M9.34268 18.7819L7.41083 18.2642L8.1983 15.3254C7.00919 14.8874 5.91661 14.2498 4.96116 13.4534L2.80783 15.6067L1.39362 14.1925L3.54695 12.0392C2.35581 10.6103 1.52014 8.87466 1.17578 6.96818L3.14386 6.61035C3.90289 10.8126 7.57931 14.0001 12.0002 14.0001C16.4211 14.0001 20.0976 10.8126 20.8566 6.61035L22.8247 6.96818C22.4803 8.87466 21.6446 10.6103 20.4535 12.0392L22.6068 14.1925L21.1926 15.6067L19.0393 13.4534C18.0838 14.2498 16.9912 14.8874 15.8021 15.3254L16.5896 18.2642L14.6578 18.7819L13.87 15.8418C13.2623 15.9459 12.6376 16.0001 12.0002 16.0001C11.3629 16.0001 10.7381 15.9459 10.1305 15.8418L9.34268 18.7819Z"/>
                      </svg>
                    ) : (
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12.0003 3C17.3924 3 21.8784 6.87976 22.8189 12C21.8784 17.1202 17.3924 21 12.0003 21C6.60812 21 2.12215 17.1202 1.18164 12C2.12215 6.87976 6.60812 3 12.0003 3ZM12.0003 19C16.2359 19 19.8603 16.052 20.7777 12C19.8603 7.94803 16.2359 5 12.0003 5C7.7646 5 4.14022 7.94803 3.22278 12C4.14022 16.052 7.7646 19 12.0003 19ZM12.0003 16.5C9.51498 16.5 7.50026 14.4853 7.50026 12C7.50026 9.51472 9.51498 7.5 12.0003 7.5C14.4855 7.5 16.5003 9.51472 16.5003 12C16.5003 14.4853 14.4855 16.5 12.0003 16.5ZM12.0003 14.5C13.381 14.5 14.5003 13.3807 14.5003 12C14.5003 10.6193 13.381 9.5 12.0003 9.5C10.6196 9.5 9.50026 10.6193 9.50026 12C9.50026 13.3807 10.6196 14.5 12.0003 14.5Z"/>
                      </svg>
                    )}
                  </button>
                </div>
              </div>
            </div>
          )}

          {!showSuccess && (
            <div className="modalFooter">
              <button
                type="button"
                onClick={onClose}
                disabled={isLoading}
                className="btnSecondary"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isLoading}
                className="btnPrimary"
              >
                {isLoading ? (
                  <>
                    <svg className="spinner" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Clocking In...
                  </>
                ) : (
                  <>
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    Clock In
                  </>
                )}
              </button>
            </div>
          )}
        </form>
      </div>
    </div>
  )
}

export default ClockInModal